### ISSUE TITLE
Newline info lost during formatting

### ISSUE THREAD

**Issue by mar-v-in** [OpenCageData/perl-Geo-Address-Formatter#3]
While information on newlines is properly stored in the [input file](https://github.com/OpenCageData/address-formatting/blob/master/conf/countries/worldwide.yaml), it is lost and replaced with "," in the perl library. As "," can occur in addresses it is not possible to create a full postal address with proper newlines from that output.

However it seems that in some country specific postforma_replace rules, you rely on the fact that newlines are replaced with "," (or at least I assume that from replacements like `["Bogota, Bogota","Bogota"]`).

Although having proper oneline addresses is already awesome, I think that having multiline addresses (as used for postal services) is even more valuable (e.g for business usage). This should obviously also be exposed in the OpenCage Geocoder API.

**Comment by freyfogle** [comment]
Thanks for commenting, this project definitely needs more eyeballs.

You are correct, this information is lost. 

The formatted address returned by the OpenCage geocoder is single line, right now we have no real plans to change this as no customer has ever told us it is a problem.

Our assumption is that anyone familiar enough with a specific country or territory will be able to convert the single line output to a correct multi-line rendering.

The "Bogota, Bogata" example and others like it are to deal with the situation that the name is both city and state/province and in general usage it is written only once as they are synonymous. Our list of such cases is hardly comprehensive though.

**Comment by freyfogle** [comment]
Hi @mar-v-in 

in version 1.52 which was released yesterday newlines are preserved. You were right, we were wrong, there is no reason to discard that information. Wish we had done it that way from the beginning.
