### ISSUE TITLE
Feature "unicode_strings" is not supported by Perl 5.10

### ISSUE THREAD

**Issue by mtmail** [OpenCageData/perl-Geo-Address-Formatter#5]
https://github.com/OpenCageData/perl-Geo-Address-Formatter/commit/77571da7e34a91f09649ab59a23edba4ad3c6474 introduces `feature "unicode_strings";`. That's not supported by older Perl versions, see http://matrix.cpantesters.org/?dist=Geo-Address-Formatter+1.54

Change the dist.ini to set a minimum required Perl version.

(Also there are two bugs in https://rt.cpan.org/Public/Dist/Display.html?Name=Geo-Address-Formatter, I think it's possible to set the issue link to github issues)

**Comment by freyfogle** [comment]
re: the RT bugs
1. the YAML bug is solved from version 1.50 onwards
2. the other bug was also solved, it was due to hash key ordering

I will see how I can resolve them

will also set a min Perl version

**Comment by mtmail** [comment]
"The issues = 1 lets CPAN use the github bugtracker rather than RT. "
http://blogs.perl.org/users/ovid/2014/03/a-simple-distini-for-distzilla.html

**Comment by freyfogle** [comment]
ok, version 1.55 on way to CPAN now, let's see if it solves all problems
